### ISSUE TITLE
Why are some items missing from data.json?

### ISSUE THREAD

**Issue by Jiayi-Pan** [X-LANCE/META-GUI-baseline#1]
Hi, thank you for this great work!

I have noticed some inconsistencies in the data.json file of the metagui dataset. Specifically, in the dev split:

- There's no data dict associated with dataset/dev/dialog_0/turn_0/5.png
- dataset/dev/dialog_0/turn_0/7.png is absent in the screenshot_history for that turn

Could you please clarify if these omissions were intended?

Thank you.

**Comment by Sunliangtai** [comment]
Sorry for replying so late, and thank you for your interest in our work.
These omissions are normal. That is because during annotation, we annotate some some action types that were not used during the training process. Also, due to some device errors, the view hierarchies for some screenshots are absent, which we deleted from the dataset. 
Your can read this [code](https://github.com/X-LANCE/META-GUI-baseline/blob/main/src/processors.py) for more information.
